### ISSUE TITLE
Complete description of mechanical part in the production guide

### ISSUE THREAD

**Issue by GG23800** [echopen/PRJ-medtec_kit#10]

**Comment by jerome2echopen** [comment]
To complete the kit, one have to 3D print some pieces locate on PRJ-medtec_kit/mecanic/modules. At least we need MDL-motor_support, MDL-rod_fixation and MDL-transducer_support, with these modules we have the stricilly minimum device to make measurement in an acquarium. Use the .stl files present in the different folders for 3d printing them. Note that for the moment MDL-transducer_support will have to be adapted for your own transducer because we have not « serial » transducers to ship with our kit yet. One can do that by using freecad (open the .igs file) modify and then export in .stl file (mesh formats files).

First print MDL-motor_support, at the end it will look to something like that:

![support_raw](https://cloud.githubusercontent.com/assets/14290878/25046759/8b27c11c-2133-11e7-9142-a07238787caa.JPG)

![support_raw2](https://cloud.githubusercontent.com/assets/14290878/25046762/93c5875a-2133-11e7-88be-5a98856cd623.JPG)

Take off the plastique support, there is still plastic in the hole where we will put the motor :

![support_raw3_2](https://cloud.githubusercontent.com/assets/14290878/25046774/a1f4587e-2133-11e7-84dc-2f13306aca71.JPG)

Take it off too with pliers for example, and it’s finish:

![support_evide](https://cloud.githubusercontent.com/assets/14290878/25046778/ab14e1f8-2133-11e7-951e-f97ca449919f.JPG)

Now fix the motor to this support with 2 or 4 screw 3 mm diameter, 6mm long.

Now print MDL-rod-fixation, the two holes on each side of this part of the cylinder. The bigger one is for the motor axe. Fix this axis with a 3mm diameter 10 mm long screw. This screw must be 10 mm minimum cause it must stick out so it will hit the motor_support when initialising (searching it's 0). The second one is used to fix the rod, prefer using wood screw 3 mm diameter.

![montage1](https://cloud.githubusercontent.com/assets/14290878/25046818/cf8b07e2-2133-11e7-9160-16d13f03c956.JPG)

The rod is a metal rod 4 mm diameter, prefer stainless steel, because it will be immersed in water, We use 100 mm long rod, but only limitation on the length is that the transducer must be immersed and the electrical connection of the transducer must not.

Then print the tranducer support and fix it to the rod.

![finish](https://cloud.githubusercontent.com/assets/14290878/25046827/dc7a2442-2133-11e7-823f-2ffeb7d1adaa.JPG)
